repositories {
    mavenCentral()
    maven {
        url "https://repo.osgeo.org/repository/release/"
    }
}

dependencies {
    compile( 'org.hibernate:hibernate-spatial:' + rootProject.hibernateVersion )
    compile( 'org.geolatte:geolatte-geom:1.3.0' )
    // GeoDB is an H2 spatial extension
    compile( 'org.opengeo:geodb:0.9' )
}
