INSERT INTO fashioncollection(id, "year", season, keywords) VALUES
    (nextval('hibernate_sequence'), 2018, 'FALL_WINTER', 'rick and morty, cartoon, science fiction'),
    (nextval('hibernate_sequence'), 2019, 'SPRING_SUMMER', 'bike, sport'),
    (nextval('hibernate_sequence'), 2019, 'FALL_WINTER', 'mountains, snow, ski, sport'),
    (nextval('hibernate_sequence'), 2020, 'SPRING_SUMMER', 'portal, video games, science fiction'),
    (nextval('hibernate_sequence'), 2020, 'FALL_WINTER', 'cosy, cabin');

INSERT INTO tshirt(id, name, collection_id)
    SELECT nextval('hibernate_sequence'), raw.name, c.id
    FROM
        (VALUES
            ('Rick and Morty portal', 2018, 'FALL_WINTER'),
            ('Morty jumping into the abyss', 2018, 'FALL_WINTER'),
            ('Flying saucer firing lasers', 2018, 'FALL_WINTER'),
            ('Morty frozen in snow', 2018, 'FALL_WINTER'),
            ('Bike logo with stripes', 2019, 'SPRING_SUMMER'),
            ('Handlebars', 2019, 'SPRING_SUMMER'),
            ('Wheels', 2019, 'SPRING_SUMMER'),
            ('Jumping over a log', 2019, 'SPRING_SUMMER'),
            ('Mountain biking', 2019, 'SPRING_SUMMER'),
            ('Everest eternal snow', 2019, 'FALL_WINTER'),
            ('Ski jump', 2019, 'FALL_WINTER'),
            ('Snowboard', 2019, 'FALL_WINTER'),
            ('Aperture Science logo ', 2020, 'SPRING_SUMMER'),
            ('GLaDOS in fire', 2020, 'SPRING_SUMMER'),
            ('Portal 2 logo', 2020, 'SPRING_SUMMER'),
            ('Still alive', 2020, 'SPRING_SUMMER'),
            ('Bear rug', 2020, 'FALL_WINTER'),
            ('Fireplace', 2020, 'FALL_WINTER'),
            ('Mountains through the window', 2020, 'FALL_WINTER')
        ) AS raw (name, "year", season)
        INNER JOIN fashioncollection c ON raw."year" = c."year" AND raw.season = c.season;

INSERT INTO tshirt_variants(tshirt_id, "variants_order", "size", color, price)
    SELECT t.id, raw.variants_order, raw."size", raw.color, raw.price
    FROM
        (VALUES
            ('Rick and Morty portal', 0, 'XXL', 'Green', 10.99),
            ('Rick and Morty portal', 1, 'XXL', 'Black', 10.99),
            ('Rick and Morty portal', 2, 'XXXL', 'Green', 11.99),
            ('Rick and Morty portal', 3, 'XXXL', 'Black', 11.99),
            ('Morty jumping into the abyss', 0, 'XXL', 'Green', 12.99),
            ('Morty jumping into the abyss', 1, 'XXL', 'Purple', 12.99),
            ('Morty jumping into the abyss', 2, 'XXXL', 'Purple', 14.99),
            ('Flying saucer firing lasers', 0, 'L', 'Yellow', 10.99),
            ('Flying saucer firing lasers', 1, 'XL', 'Yellow', 10.99),
            ('Flying saucer firing lasers', 2, 'XXL', 'Yellow', 11.59),
            ('Morty frozen in snow', 0, 'L', 'White', 9.99),
            ('Morty frozen in snow', 1, 'XL', 'White', 10.99),
            ('Morty frozen in snow', 2, 'XXL', 'White', 10.99),
            ('Morty frozen in snow', 3, 'XXXL', 'White', 14.99),
            ('Bike logo with stripes', 0, 'XS', 'Grey and green', 7.99),
            ('Bike logo with stripes', 1, 'S', 'Grey and green', 9.99),
            ('Bike logo with stripes', 2, 'M', 'Grey and green', 9.99),
            ('Bike logo with stripes', 3, 'L', 'Grey and green', 10.99),
            ('Bike logo with stripes', 4, 'XL', 'Grey and green', 10.99),
            ('Handlebars', 0, 'XS', 'Red', 8.99),
            ('Handlebars', 1, 'S', 'Red', 9.99),
            ('Handlebars', 2, 'M', 'Red', 9.99),
            ('Handlebars', 3, 'L', 'Red', 9.99),
            ('Handlebars', 4, 'XL', 'Red', 10.99),
            ('Wheels', 0, 'XS', 'Grey', 8.99),
            ('Wheels', 1, 'S', 'Grey', 9.99),
            ('Wheels', 2, 'S', 'Blue', 9.99),
            ('Wheels', 3, 'M', 'Grey', 9.99),
            ('Wheels', 4, 'M', 'Blue', 9.99),
            ('Wheels', 5, 'L', 'Grey', 9.99),
            ('Wheels', 6, 'L', 'Blue', 9.99),
            ('Wheels', 7, 'XL', 'Blue', 10.99),
            ('Jumping over a log', 0, 'S', 'Orange', 9.99),
            ('Jumping over a log', 1, 'M', 'Orange', 9.99),
            ('Jumping over a log', 2, 'L', 'Orange', 9.99),
            ('Jumping over a log', 3, 'XL', 'Orange', 9.99),
            ('Mountain biking', 0, 'XS', 'Grey', 8.99),
            ('Mountain biking', 1, 'S', 'Grey', 9.99),
            ('Mountain biking', 2, 'S', 'Red', 9.99),
            ('Mountain biking', 3, 'M', 'Grey', 9.99),
            ('Mountain biking', 4, 'M', 'Red', 9.99),
            ('Mountain biking', 5, 'L', 'Grey', 9.99),
            ('Mountain biking', 6, 'L', 'Red', 9.99),
            ('Mountain biking', 7, 'XL', 'Red', 9.99),
            ('Everest eternal snow', 0, 'S', 'Mauve', 10.99),
            ('Everest eternal snow', 1, 'M', 'Mauve', 10.99),
            ('Everest eternal snow', 2, 'L', 'Mauve', 10.99),
            ('Everest eternal snow', 3, 'XL', 'Mauve', 10.99),
            ('Ski jump', 0, 'S', 'White', 9.99),
            ('Ski jump', 1, 'M', 'White', 9.99),
            ('Ski jump', 2, 'L', 'White', 9.99),
            ('Ski jump', 3, 'XL', 'White', 9.99),
            ('Snowboard', 0, 'S', 'Blue', 9.99),
            ('Snowboard', 1, 'M', 'Blue', 9.99),
            ('Snowboard', 2, 'L', 'Blue', 9.99),
            ('Snowboard', 3, 'XL', 'Blue', 9.99),
            ('Aperture Science logo ', 0, 'S', 'Black and white', 8.99),
            ('Aperture Science logo ', 1, 'M', 'Black and white', 9.99),
            ('Aperture Science logo ', 2, 'L', 'Black and white', 9.99),
            ('Aperture Science logo ', 3, 'XL', 'Black and white', 9.99),
            ('Aperture Science logo ', 4, 'XXL', 'Black and white', 11.99),
            ('GLaDOS in fire', 0, 'S', 'Black', 9.99),
            ('GLaDOS in fire', 1, 'M', 'Black', 9.99),
            ('GLaDOS in fire', 2, 'L', 'Black', 9.99),
            ('GLaDOS in fire', 3, 'XL', 'Black', 9.99),
            ('GLaDOS in fire', 4, 'XXL', 'Black', 9.99),
            ('Portal 2 logo', 0, 'S', 'Blue', 9.99),
            ('Portal 2 logo', 1, 'M', 'Blue', 9.99),
            ('Portal 2 logo', 2, 'L', 'Blue', 9.99),
            ('Portal 2 logo', 3, 'XL', 'Blue', 9.99),
            ('Still alive', 0, 'S', 'Pink', 10.99),
            ('Still alive', 1, 'M', 'Pink', 10.99),
            ('Still alive', 2, 'L', 'Pink', 10.99),
            ('Still alive', 3, 'XL', 'Pink', 10.99),
            ('Bear rug', 0, 'XS', 'Brown', 17.99),
            ('Bear rug', 1, 'S', 'Brown', 19.99),
            ('Bear rug', 2, 'M', 'Brown', 19.99),
            ('Bear rug', 3, 'L', 'Brown', 19.99),
            ('Bear rug', 4, 'XL', 'Brown', 21.99),
            ('Fireplace', 0, 'XS', 'Black', 17.99),
            ('Fireplace', 1, 'S', 'Black', 18.99),
            ('Fireplace', 2, 'M', 'Black', 19.99),
            ('Fireplace', 3, 'L', 'Black', 19.99),
            ('Fireplace', 4, 'XL', 'Black', 20.99),
            ('Mountains through the window', 0, 'XS', 'Dark blue', 15.99),
            ('Mountains through the window', 1, 'S', 'Dark blue', 16.99),
            ('Mountains through the window', 2, 'M', 'Dark blue', 17.99),
            ('Mountains through the window', 3, 'L', 'Dark blue', 17.99),
            ('Mountains through the window', 4, 'XL', 'Dark blue', 18.99)
        ) AS raw (tshirtname, variants_order, "size", color, price)
        INNER JOIN tshirt t ON raw.tshirtname = t.name;
