# Hibernate Demo: Message Board
Data MicroService Demo.

Made with Hibernate ORM, Hibernate OGM and Infinispan for OpenShift Container Platform. 

## Pre-Requirement

* Java 8
* Maven 3+
* NPM (https://www.npmjs.com/)
* Angular Cli (npm install -g @angular/cli) [avoid 6.1.x]
* OpenShift (3.7+) client

## Build demo
----
mvn clean install
----

## Deploy Infinispan custom Docker image
----
cd script
sh ./install-custom-infinispan-image.sh
----

## Install demo
----
cd script

( oc login -u [YOUR-USER-NAME] ) <<optional>>
( oc new-project [YOUR-PROJECT-NAME] ) <<optional>>

sh ./install-all.sh
----

## Update Account MicroService
----
cd script
sh ./binary-build-account.sh
----

## Update Message MicroService
----
cd script
sh ./binary-build-message.sh
----

## Update Web App
----
cd script
sh ./binary-build-web.sh
----

## Test

### Web [FORM]

[YOUR-USER-NAME] is your OCP username like **developer**
[YOUR-PROJECT-NAME] is your OCP project like **message-board**
[YOUR-IP] is a generate IP by OCP like **192.168.42.120**

----
http://web-message-board.[YOUR-IP].nip.io
----

click on __andrea__ or __fabio__

### Message MicroService [REST]
#### with proxy
----
http://web-message-board.[YOUR-IP].nip.io/message-service/messages?username=andrea
----
#### without proxy
----
http://message-service-message-board.[YOUR-IP].nip.io/message-service/messages?username=andrea
----

### Account MicroService [REST]
#### with proxy
----
http://web-message-board.[YOUR-IP].nip.io/account-service/user
----
#### without proxy
----
http://account-service-message-board.[YOUR-IP].nip.io/account-service/user
----

## Known Issues

### NodeJs module Angular cli 6.1.x
It seems there is an issue on angular-cli versions 6.1.0 and 6.1.1.
It might need to downgrade angular-cli version:
----
sudo -s npm uninstall -g @angular/cli
sudo -s npm install -g @angular/cli@6.0.8
----
For more information see https://github.com/angular/angular-cli/issues/11661[Issue Page].

### MiniShift CDK v3.5.0-1
Actually there is an issue with MiniShift v1.20.0+1bd6d5c, CDK v3.5.0-1.
The persistent volume for Infinispan server pod is mounted as root user.