name: GH Actions CI

on:
  push:
    branches-ignore:
      # We don't want to run CI on branches for dependabot, just on the PR.
      - 'dependabot/**'
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Set up JDK 17
      uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    - name: Build
      run: mvn -f hibernate-search -B clean package -DskipTests=true -Dtest.containers.run.skip=true
    - name: Test
      run: mvn -f hibernate-search -B verify -Dstart-containers
